CREATE TABLE IF NOT EXISTS LESSON
(
    ID            INT  NOT NULL,
    BEGIN         DATE NOT NULL,
    END           DATE NOT NULL,
    ROOM_ID       INT  NOT NULL,
    TEACHER_ID    INT  NOT NULL,
    LESSONTYPE_ID INT  NOT NULL,
    content       TEXT NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY  (ROOM_ID) REFERENCES Room (ID),
    FOREIGN KEY (TEACHER_ID) REFERENCES TEACHER (ID),
    FOREIGN KEY (LESSONTYPE_ID) REFERENCES LESSONTYPE (ID)
);
