spring:
    profiles: dev
server:
    port: 5000
    shutdown: graceful

management:
    health:
        probes:
            enabled: true

token:
    authenticationUrl: '/authenticate'
    publicUrl: '/v1'
    secret: 'rS2wZjIMH8Di8zSEQaIf'

jdbc: 'jdbc:h2:mem:'
