INSERT INTO ROLE (ID, DESCRIPTION)
VALUES (1, 'admin');

INSERT INTO ROLE (ID, DESCRIPTION)
VALUES (2, 'teacher');

INSERT INTO ROLE (ID, DESCRIPTION)
VALUES (3, 'student');

-- Only for demo usage:

-- Admin
INSERT INTO USER (ID, USERNAME, PASSWORD, ROLE_ID, MAIL)
VALUES (1, 'admin', '1234', 1, 'admin@stage.de');

-- Teacher 1
-- INSERT INTO USER (ID, USERNAME, PASSWORD, ROLE_ID, MAIL)
-- VALUES (2, 'peter', '4321', 2, 'peter@stage.de');
--
-- INSERT INTO TEACHER (ID, LAST_NAME, FIRST_NAME, PLACE_OF_BIRTH, PHONE, ADDRESS, IBAN, BIRTHDAY)
-- VALUES (2, 'Pan', 'Peter', 'Cologne', '0221/123456', 'High Street 13', 'IBAN', '1978-4-2');
--
-- -- Teacher 2
-- INSERT INTO USER (ID, USERNAME, PASSWORD, ROLE_ID, MAIL)
-- VALUES (3, 'lisa', '0987', 2, 'lisa@stage.de');
--
-- INSERT INTO TEACHER (ID, LAST_NAME, FIRST_NAME, PLACE_OF_BIRTH, PHONE, ADDRESS, IBAN, BIRTHDAY)
-- VALUES (3, 'Smith', 'Lisa', 'Bonn', '0221/123456', 'High Street 5', 'IBAN', '1960-9-6');

-- Student 1
INSERT INTO USER (ID, USERNAME, PASSWORD, ROLE_ID, MAIL)
VALUES (4, 'bob', '5678', 3, 'bob@stage.de');

INSERT INTO STUDENT (ID, LAST_NAME, FIRST_NAME, PLACE_OF_BIRTH, PHONE, ADDRESS, IBAN, BIRTHDAY)
VALUES (4, 'the Builder', 'Bob', 'Cologne', '0221/123456', 'High Street 5', 'IBAN', '2000-5-1');

-- Student 2
INSERT INTO USER (ID, USERNAME, PASSWORD, ROLE_ID, MAIL)
VALUES (5, 'luke', '9012', 3, 'luke@stage.de');

INSERT INTO STUDENT (ID, LAST_NAME, FIRST_NAME, PLACE_OF_BIRTH, PHONE, ADDRESS, IBAN, BIRTHDAY)
VALUES (5, 'Skywalker', 'Luke', 'Tatooine', '0221/123456', 'Mos Eisley', 'IBAN', '1977-1-1');

-- Room 1
INSERT INTO Room(ID, NAME, SUITABILITY) VALUES (6,'TROMPETENRAUM', 'YES');

-- ROOM 2
INSERT INTO Room(ID, NAME, SUITABILITY) VALUES (7, 'RELAXRAUM', 'YES');

COMMIT;
