CREATE TABLE IF NOT EXISTS ROLES
(
    ID          INT  NOT NULL,
    DESCRIPTION TEXT NOT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS USERS
(
    ID       INT  NOT NULL,
    USERNAME TEXT NOT NULL,
    PWD      TEXT NOT NULL,
    MAIL     TEXT NOT NULL,
    ROLES_ID INT  NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (ROLES_ID) REFERENCES ROLES (ID)
);

CREATE TABLE IF NOT EXISTS STUDENT
(
    ID             INT  NOT NULL,
    FIRST_NAME     TEXT NOT NULL,
    LAST_NAME      TEXT NOT NULL,
    BIRTHDAY       DATE NOT NULL,
    PLACE_OF_BIRTH TEXT NOT NULL,
    ADDRESS        TEXT NOT NULL,
    PHONE          TEXT NOT NULL,
    IBAN           TEXT NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES USERS (ID)
);

CREATE TABLE IF NOT EXISTS ROOM
(
    ID          INT  NOT NULL,
    NAME        TEXT NOT NULL,
    SUITABILITY TEXT,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE IF NOT EXISTS USER_ID_SEQUENCE START WITH 1;

CREATE SEQUENCE IF NOT EXISTS ROOM_ID_SEQUENCE START WITH 1;

-- CREATE TABLE IF NOT EXISTS LESSON
-- (
--     ID            INT  NOT NULL,
--     BEGIN         DATE NOT NULL,
--     END           DATE NOT NULL,
--     ROOM_ID       INT  NOT NULL,
--     TEACHER_ID    INT  NOT NULL,
--     LESSON_TYPE_ID INT  NOT NULL,
--     CONTENT       TEXT NOT NULL,
--
--     PRIMARY KEY (ID),
--     FOREIGN KEY (ROOM_ID) REFERENCES ROOM (ID),
--     FOREIGN KEY (TEACHER_ID) REFERENCES TEACHER (ID),
--     FOREIGN KEY (LESSON_TYPE_ID) REFERENCES LESSON_TYPE (ID)
-- );

INSERT INTO ROLES (ID, DESCRIPTION)
VALUES (1, 'ADMIN');

INSERT INTO ROLES (ID, DESCRIPTION)
VALUES (2, 'TEACHER');

INSERT INTO ROLES (ID, DESCRIPTION)
VALUES (3, 'STUDENT');

-- ONLY FOR DEMO USAGE:

-- ADMIN
INSERT INTO USERS (ID, USERNAME, PWD, ROLES_ID, MAIL)
VALUES ((SELECT NEXT VALUE FOR USER_ID_SEQUENCE), 'admin', '1234', 1, 'admin@stage.de');

-- TEACHER 1
-- INSERT INTO USERS (ID, USERNAME, PWD, ROLES_ID, MAIL)
-- VALUES (2, 'PETER', '4321', 2, 'PETER@STAGE.DE');
--
-- INSERT INTO TEACHER (ID, LAST_NAME, FIRST_NAME, PLACE_OF_BIRTH, PHONE, ADDRESS, IBAN, BIRTHDAY)
-- VALUES (2, 'PAN', 'PETER', 'COLOGNE', '0221/123456', 'HIGH STREET 13', 'IBAN', '1978-4-2');
--
-- -- TEACHER 2
-- INSERT INTO USERS (ID, USERNAME, PWD, ROLES_ID, MAIL)
-- VALUES (3, 'LISA', '0987', 2, 'LISA@STAGE.DE');
--
-- INSERT INTO TEACHER (ID, LAST_NAME, FIRST_NAME, PLACE_OF_BIRTH, PHONE, ADDRESS, IBAN, BIRTHDAY)
-- VALUES (3, 'SMITH', 'LISA', 'BONN', '0221/123456', 'HIGH STREET 5', 'IBAN', '1960-9-6');

-- STUDENT 1
SET @BOB_ID = (SELECT NEXT VALUE FOR USER_ID_SEQUENCE);
INSERT INTO USERS (ID, USERNAME, PWD, ROLES_ID, MAIL)
VALUES (@BOB_ID, 'Bob', '5678', 3, 'bob@stage.de');

INSERT INTO STUDENT (ID, LAST_NAME, FIRST_NAME, PLACE_OF_BIRTH, PHONE, ADDRESS, IBAN, BIRTHDAY)
VALUES (@BOB_ID, 'the Builder', 'Bob', 'Cologne', '0221/123456', 'High Street 5',
        'IBAN', '2000-5-1');

-- STUDENT 2
SET @LUKE_ID = (SELECT NEXT VALUE FOR USER_ID_SEQUENCE);
INSERT INTO USERS (ID, USERNAME, PWD, ROLES_ID, MAIL)
VALUES (@LUKE_ID, 'Luke', '9012', 3, 'luke@stage.de');

INSERT INTO STUDENT (ID, LAST_NAME, FIRST_NAME, PLACE_OF_BIRTH, PHONE, ADDRESS, IBAN, BIRTHDAY)
VALUES (@LUKE_ID, 'Skywalker', 'Luke', 'Tatooine', '0221/123456', 'Mos Eisley', 'IBAN',
        '1977-1-1');

-- ROOM 1
INSERT INTO ROOM(ID, NAME, SUITABILITY)
VALUES (1, 'A1', 'large groups');

-- ROOM 2
INSERT INTO ROOM(ID, NAME, SUITABILITY)
VALUES (2, 'B1', 'drums');

COMMIT;
