CREATE TABLE IF NOT EXISTS STUDENT
(
    ID             INT  NOT NULL,
    FIRST_NAME     TEXT NOT NULL,
    LAST_NAME      TEXT NOT NULL,
    BIRTHDAY       DATE NOT NULL,
    PLACE_OF_BIRTH TEXT NOT NULL,
    ADDRESS        TEXT NOT NULL,
    PHONE          TEXT NOT NULL,
    IBAN           TEXT NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES USERS (ID)
);
